import React from 'react';
import Link from 'next/link';

// Using standard Tailwind classes combined with general ShadCN component patterns (Cards)
// If you have `components/ui/card` generated by Shadcn, you would import those primitives here.
// For now, we simulate the ShadCN `Card` structure with Tailwind CSS.

interface CourseCardProps {
  _id: string;
  title: string;
  description: string;
  totalLessons: number;
  href: string;
}

export const CourseCard: React.FC<CourseCardProps> = ({ _id, title, description, totalLessons, href }) => {
  return (
    <div className="rounded-xl border bg-card text-card-foreground shadow-sm overflow-hidden flex flex-col hover:shadow-md transition-shadow">
      <div className="p-6 flex flex-col gap-1.5 flex-1">
        <h3 className="font-semibold leading-none tracking-tight text-xl">{title}</h3>
        <p className="text-sm text-muted-foreground flex-1 mt-2 line-clamp-2">
          {description}
        </p>
      </div>
      <div className="p-6 pt-0 flex items-center justify-between border-t bg-muted/20 mt-auto">
        <span className="text-xs font-medium bg-secondary text-secondary-foreground px-2.5 py-1 rounded-md">
          {totalLessons} Lessons
        </span>
        <Link 
          href={href}
          className="inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-primary text-primary-foreground hover:bg-primary/90 h-9 px-4 py-2"
        >
          View Course
        </Link>
      </div>
    </div>
  );
};
